server:
  port: 8086

spring:
  application:
    name: basket-service

  data:
    redis:
      host: ${REDIS_HOST:redis-cache}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://tempo:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
