#!/usr/bin/env bash
# ============================================================
#  generate-secrets.sh
#  Generates a cryptographically secure .env file for local
#  development.  Run this once when setting up the project:
#
#    chmod +x generate-secrets.sh
#    ./generate-secrets.sh
#
#  The generated .env is read automatically by Docker Compose.
#  NEVER commit .env — it is gitignored.
# ============================================================

set -euo pipefail

ENV_FILE=".env"

# ── Guard ────────────────────────────────────────────────────
if [ -f "$ENV_FILE" ]; then
  echo ""
  echo "  .env already exists."
  echo "  Delete it first if you want to regenerate:"
  echo "    rm .env && ./generate-secrets.sh"
  echo ""
  exit 1
fi

# ── Check dependencies ───────────────────────────────────────
if ! command -v openssl &>/dev/null; then
  echo "Error: openssl is required but not installed."
  exit 1
fi

# ── Generate secrets ─────────────────────────────────────────
JWT_SECRET=$(openssl rand -hex 32)

# ── Write .env ───────────────────────────────────────────────
cat > "$ENV_FILE" << EOF
# ============================================================
#  Generated by generate-secrets.sh on $(date)
#  DO NOT commit this file — it is gitignored.
#  To regenerate: rm .env && ./generate-secrets.sh
# ============================================================

# --- JWT ---
# 256-bit secret shared between user-service and gateway-service
JWT_SECRET=${JWT_SECRET}

# --- Database ---
POSTGRES_USER=user
POSTGRES_PASSWORD=password

# --- Redis ---
REDIS_HOST=redis-cache
REDIS_PORT=6379
EOF

chmod 600 "$ENV_FILE"   # Only the owner can read/write

echo ""
echo "  .env created successfully."
echo "  JWT_SECRET: ${JWT_SECRET:0:8}...  (truncated for safety)"
echo ""
echo "  Start your services:"
echo "    docker compose up --build"
echo ""
