#!/usr/bin/env bash
# ============================================================
#  start.sh — Build and run the Food Ordering System
#
#  Usage:
#    ./start.sh           # normal start
#    ./start.sh --clean   # wipe volumes (fresh DB) before start
#    ./start.sh --rebuild # force Maven + Docker rebuild
# ============================================================

set -euo pipefail

# ── Colours ──────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Colour

step()  { echo -e "\n${CYAN}▶ $1${NC}"; }
ok()    { echo -e "${GREEN}✔ $1${NC}"; }
warn()  { echo -e "${YELLOW}⚠ $1${NC}"; }
error() { echo -e "${RED}✖ $1${NC}"; exit 1; }

# ── Flags ─────────────────────────────────────────────────────
CLEAN=false
REBUILD=false
for arg in "$@"; do
  case $arg in
    --clean)   CLEAN=true ;;
    --rebuild) REBUILD=true ;;
    *) error "Unknown argument: $arg. Use --clean or --rebuild." ;;
  esac
done

# ════════════════════════════════════════════════════════════
#  STEP 0 — Install git hooks (idempotent)
# ════════════════════════════════════════════════════════════
step "Installing git hooks..."

GIT_HOOK=".git/hooks/pre-commit"
if [ ! -f "$GIT_HOOK" ] || ! grep -q "enforce-conventions" "$GIT_HOOK" 2>/dev/null; then
  cat > "$GIT_HOOK" <<'HOOKEOF'
#!/usr/bin/env bash
set -e
REPO_ROOT=$(git rev-parse --show-toplevel)
"$REPO_ROOT/.claude/hooks/pre-commit/enforce-conventions"
"$REPO_ROOT/.claude/hooks/pre-commit/secret-scanner"
"$REPO_ROOT/.claude/hooks/pre-commit/flyway-migration-safety"
HOOKEOF
  chmod +x "$GIT_HOOK"
  ok "Git pre-commit hook installed"
else
  ok "Git pre-commit hook already installed"
fi

# ════════════════════════════════════════════════════════════
#  STEP 1 — Check prerequisites
# ════════════════════════════════════════════════════════════
step "Checking prerequisites..."

command -v java        &>/dev/null || error "Java is not installed."
command -v docker      &>/dev/null || error "Docker is not installed."
command -v docker      &>/dev/null && docker compose version &>/dev/null || error "Docker Compose plugin is not installed."

ok "Java:   $(java -version 2>&1 | head -1)"
ok "Docker: $(docker --version)"

# ════════════════════════════════════════════════════════════
#  STEP 2 — Generate secrets (only if .env does not exist)
# ════════════════════════════════════════════════════════════
step "Checking secrets..."

if [ -f ".env" ]; then
  ok ".env already exists — skipping secret generation."
else
  warn ".env not found — generating secrets..."

  command -v openssl &>/dev/null || error "openssl is required to generate secrets but is not installed."

  JWT_SECRET=$(openssl rand -hex 32)

  cat > .env << EOF
# ============================================================
#  Generated by start.sh on $(date)
#  DO NOT commit this file — it is gitignored.
# ============================================================

JWT_SECRET=${JWT_SECRET}

POSTGRES_USER=user
POSTGRES_PASSWORD=password

REDIS_HOST=redis-cache
REDIS_PORT=6379
EOF

  chmod 600 .env
  ok ".env created (JWT_SECRET=${JWT_SECRET:0:8}...)"
fi

# ════════════════════════════════════════════════════════════
#  STEP 3 — Build with Maven (skip if JARs exist and no --rebuild)
# ════════════════════════════════════════════════════════════
step "Building services..."

JARS=(
  "user-service/target"
  "analytics-service/target"
  "order-service/target"
  "payment-service/target"
  "product-service/target"
)

needs_build() {
  for dir in "${JARS[@]}"; do
    ls "$dir"/*.jar 2>/dev/null | grep -v original &>/dev/null || return 0
  done
  return 1
}

if $REBUILD || needs_build; then
  echo "  Running: ./mvnw clean install -DskipTests"
  ./mvnw clean install -DskipTests || error "Maven build failed. Fix the errors above and re-run."
  ok "Build successful."
else
  ok "JARs already exist — skipping build. Use --rebuild to force."
fi

# ════════════════════════════════════════════════════════════
#  STEP 4 — Start Docker Compose
# ════════════════════════════════════════════════════════════
step "Starting Docker Compose..."

if $CLEAN; then
  warn "--clean flag set: removing volumes (database will be wiped)."
  docker compose down -v
elif docker compose ps -q 2>/dev/null | grep -q .; then
  warn "Services already running — stopping them first."
  docker compose down
fi

docker compose up --build -d

# ════════════════════════════════════════════════════════════
#  STEP 5 — Wait for services to be healthy
# ════════════════════════════════════════════════════════════
step "Waiting for services to start..."

wait_for() {
  local name=$1
  local url=$2
  local retries=30
  local wait=3

  echo -n "  Waiting for $name"
  for i in $(seq 1 $retries); do
    if curl -sf "$url" &>/dev/null; then
      echo -e " ${GREEN}✔${NC}"
      return 0
    fi
    echo -n "."
    sleep $wait
  done
  echo -e " ${RED}✖${NC}"
  warn "$name did not become healthy in time. Check logs: docker compose logs $name"
  return 1
}

wait_for "user-service"      "http://localhost:8081/actuator/health"
wait_for "analytics-service" "http://localhost:8082/actuator/health"
wait_for "order-service"     "http://localhost:8083/actuator/health"
wait_for "payment-service"   "http://localhost:8084/actuator/health"
wait_for "product-service"   "http://localhost:8085/actuator/health"

# ════════════════════════════════════════════════════════════
#  Done
# ════════════════════════════════════════════════════════════
echo ""
echo -e "${GREEN}════════════════════════════════════════${NC}"
echo -e "${GREEN}  Food Ordering System is running!${NC}"
echo -e "${GREEN}════════════════════════════════════════${NC}"
echo ""
echo "  Services (direct access — no gateway):"
echo "    user-service:      http://localhost:8081"
echo "    analytics-service: http://localhost:8082"
echo "    order-service:     http://localhost:8083"
echo "    payment-service:   http://localhost:8084"
echo "    product-service:   http://localhost:8085"
echo ""
echo "  Grafana:   http://localhost:3000"
echo ""
echo "  Quick test:"
echo "    curl -s -X POST http://localhost:8081/api/v1/users \\"
echo "      -H 'Content-Type: application/json' \\"
echo "      -d '{\"username\":\"john\",\"password\":\"secret123\",\"email\":\"john@test.com\",\"role\":\"USER\"}'"
echo ""
echo "  View logs:  docker compose logs -f user-service"
echo "  Stop:       docker compose down"
echo ""
