CREATE DATABASE user_db;
CREATE DATABASE order_db;
CREATE DATABASE payment_db;

GRANT ALL PRIVILEGES ON DATABASE user_db TO "user";
GRANT ALL PRIVILEGES ON DATABASE order_db TO "user";
GRANT ALL PRIVILEGES ON DATABASE payment_db TO "user";