# ── user-service IRSA role ────────────────────────────────────────────────────
# Naming: {org}-{env}-{service}-irsa (per BUILD-PLAN.md §2.7 deploy template)

resource "aws_iam_role" "user_service_irsa" {
  name = "food-delivery-production-user-service-irsa"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Federated = module.eks.oidc_provider_arn }
      Action    = "sts:AssumeRoleWithWebIdentity"
      Condition = {
        StringEquals = {
          # oidc_provider_url already strips the https:// prefix
          "${module.eks.oidc_provider_url}:sub" = "system:serviceaccount:identity:user-service"
          "${module.eks.oidc_provider_url}:aud" = "sts.amazonaws.com"
        }
      }
    }]
  })

  tags = { Service = "user-service" }
}

resource "aws_iam_role_policy" "user_service_irsa" {
  name = "user-service-policy"
  role = aws_iam_role.user_service_irsa.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      # ── Secrets Manager ──────────────────────────────────────────────────────
      {
        Sid    = "ReadServiceSecrets"
        Effect = "Allow"
        Action = ["secretsmanager:GetSecretValue", "secretsmanager:DescribeSecret"]
        Resource = [
          aws_secretsmanager_secret.user_service_db.arn,
          aws_secretsmanager_secret.user_service_jwt_key.arn,
          module.redis.auth_token_secret_arn,
        ]
      },
      # ── SSM Parameter Store ──────────────────────────────────────────────────
      # App publishes the RS256 public key to SSM at startup so API Gateway's
      # Lambda authorizer can read it without holding the private key.
      {
        Sid    = "JwtPublicKeySSM"
        Effect = "Allow"
        Action = ["ssm:GetParameter", "ssm:PutParameter"]
        Resource = "arn:aws:ssm:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:parameter/food-delivery/user-service/*"
      },
      # ── MSK IAM auth ─────────────────────────────────────────────────────────
      # user-service produces to the user-events topic via the transactional outbox.
      {
        Sid    = "MSKConnect"
        Effect = "Allow"
        Action = ["kafka-cluster:Connect", "kafka-cluster:AlterCluster", "kafka-cluster:DescribeCluster"]
        Resource = module.msk.cluster_arn
      },
      {
        Sid    = "MSKTopics"
        Effect = "Allow"
        Action = ["kafka-cluster:*Topic*", "kafka-cluster:WriteData", "kafka-cluster:ReadData"]
        Resource = "arn:aws:kafka:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:topic/food-delivery-production/*"
      },
      {
        Sid    = "MSKGroups"
        Effect = "Allow"
        Action = ["kafka-cluster:AlterGroup", "kafka-cluster:DescribeGroup"]
        Resource = "arn:aws:kafka:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:group/food-delivery-production/*"
      },
    ]
  })
}

# ── JWT RS256 key pair ────────────────────────────────────────────────────────
# Private key generated by Terraform and stored in Secrets Manager.
# The app loads it at startup via AWS SDK using JWT_PRIVATE_KEY_SECRET_ARN.
# The corresponding public key is published by the app to SSM at startup.

resource "tls_private_key" "user_service_jwt" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "aws_secretsmanager_secret" "user_service_jwt_key" {
  name        = "food-delivery/production/user-service/jwt-private-key"
  description = "RS256 private key for user-service JWT issuance"
  kms_key_id  = aws_kms_key.sns_sqs.arn

  tags = { Service = "user-service" }
}

resource "aws_secretsmanager_secret_version" "user_service_jwt_key" {
  secret_id     = aws_secretsmanager_secret.user_service_jwt_key.id
  secret_string = tls_private_key.user_service_jwt.private_key_pem
}

# ── DB credentials ────────────────────────────────────────────────────────────
# Populated with the cluster endpoint automatically.
# DB_USERNAME and DB_PASSWORD must be updated after creating the identity_user
# in RDS (run the SQL in docs/plan/BUILD-PLAN.md step 2.1).

resource "aws_secretsmanager_secret" "user_service_db" {
  name        = "food-delivery/production/user-service/db"
  description = "Database connection credentials for user-service (identity_db)"
  kms_key_id  = aws_kms_key.sns_sqs.arn

  tags = { Service = "user-service" }
}

resource "aws_secretsmanager_secret_version" "user_service_db" {
  secret_id = aws_secretsmanager_secret.user_service_db.id

  secret_string = jsonencode({
    DB_URL      = "jdbc:postgresql://${module.rds.cluster_endpoint}:${module.rds.port}/identity_db"
    DB_USERNAME = "identity_user"
    DB_PASSWORD = "REPLACE_AFTER_TF_APPLY"
  })
}

# ── Outputs ───────────────────────────────────────────────────────────────────

output "user_service_irsa_role_arn" {
  description = "IRSA role ARN — paste into apps/user-service/base/serviceaccount.yaml"
  value       = aws_iam_role.user_service_irsa.arn
}

output "user_service_jwt_key_secret_arn" {
  description = "JWT private key secret ARN — paste into apps/user-service/overlays/production/configmap-patch.yaml"
  value       = aws_secretsmanager_secret.user_service_jwt_key.arn
}

output "user_service_db_secret_arn" {
  description = "DB credentials secret ARN"
  value       = aws_secretsmanager_secret.user_service_db.arn
}
