server:
  port: 8087

spring:
  application:
    name: kitchen-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    consumer:
      group-id: kitchen-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "food.delivery.system.*"

aws:
  region: ${AWS_REGION:us-east-1}
  dynamodb:
    endpoint: ${AWS_DYNAMODB_ENDPOINT:}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://tempo:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
